env:
  browser: true
  node: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:vue/vue3-recommended
  - "@nuxtjs/eslint-config-typescript"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.eslint.json"
  extraFileExtensions:
    - ".vue"
rules:
  # @nuxtjs/eslint-config-typescript によって再設定されるので無効化
  accessor-pairs: off
  brace-style: off
  camelcase: off
  comma-dangle: off
  comma-spacing: off
  dot-notation: off
  func-call-spacing: off
  indent: off
  keyword-spacing: off
  lines-between-class-members: off
  multiline-ternary: off
  no-array-constructor: off
  no-dupe-class-members: off
  no-extra-parens: off
  no-implied-eval: off
  no-loss-of-precision: off
  no-new-func: off
  no-redeclare: off
  no-shadow: off
  no-spaced-func: off
  no-throw-literal: off
  no-unmodified-loop-condition: off
  no-unused-expressions: off
  no-unused-vars: off
  no-use-before-define: off
  no-useless-call: off
  no-useless-constructor: off
  object-curly-spacing: off
  quotes: off
  require-await: off
  semi: off
  space-before-blocks: off
  space-before-function-paren: off
  space-infix-ops: off
  # vue3で推奨される記述を許可
  vue/no-v-for-template-key: off
  vue/no-v-for-template-key-on-child: error
  vue/no-multiple-template-root: off
  vue/no-v-model-argument: off
  # HTMLの記述の幅を狭めるので除去
  vue/singleline-html-element-content-newline: off
  # 不使用の変数を許可(警告は出す)
  "@typescript-eslint/no-unused-vars": warn
  # 同名の変数を許可
  "@typescript-eslint/no-shadow": off
  vue/no-template-shadow: off
  # インポート時の拡張子省略
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  # オブジェクトキーの引用符
  quote-props:
    - error
    - consistent
  # 行の最大コード量
  max-len:
    - warn
    - code: 120
      tabWidth: 2
      comments: 100
      ignoreComments: false
      ignoreTrailingComments: false
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  vue/max-len:
    - warn
    - code: 120
      template: 150
      tabWidth: 2
      comments: 100
      ignoreComments: false
      ignoreTrailingComments: false
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
      ignoreHTMLAttributeValues: false
      ignoreHTMLTextContents: false
  # パフォーマンスの悪いルールのため無効化
  import/namespace: off
overrides:
  # vueコンポーネントのみの設定
  - files:
      - "**/*.vue"
    rules:
      max-len: off
  # 一部のコンポーネントは一単語の命名を許可
  - files:
      - "src/pages/**/*.vue"
      - "src/layouts/**/*.vue"
    rules:
      vue/multi-word-component-names: off
  # 一部の処理で一貫性のないreturnを許可
  - files:
      - "src/middleware/**/*"
    rules:
      consistent-return: off
  # defineNuxtConfig を importするため無効化
  - files:
      - nuxt.config.ts
    rules:
      import/no-extraneous-dependencies: off
